# Generated by Django 3.2.5 on 2021-07-21 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Big Warehouse', max_length=256)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('measurement_unit', models.CharField(choices=[('feet', 'Feet'), ('inches', 'Inches')], default='inches', max_length=20)),
                ('length', models.PositiveIntegerField(default=600)),
                ('width', models.PositiveIntegerField(default=600)),
                ('height', models.PositiveIntegerField(default=120)),
                ('lane_width_size', models.PositiveIntegerField(default=48)),
                ('shelf_length', models.PositiveIntegerField(default=120)),
                ('shelf_depth', models.PositiveIntegerField(default=48)),
                ('shelf_height', models.PositiveIntegerField(default=60)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=256)),
                ('units_in_inventory', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('units_recieved', models.PositiveIntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse')),
            ],
        ),
    ]
