# Generated by Django 3.2.5 on 2021-07-19 20:28

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        # HStoreExtension(),
        migrations.AddField(
            model_name='warehouse',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='grid',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), size=None), size=None), default=0, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='lane_width_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='leftover_x_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelves',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='x_grid_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='y_grid_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='z_grid_space',
            field=models.IntegerField(default=0),
        ),
    ]
