# Generated by Django 3.2.5 on 2021-07-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='height',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='lane_width_size',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='length',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='measurement_unit',
            field=models.CharField(choices=[('feet', 'Feet'), ('inches', 'Inches')], default='inches', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelf_depth',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelf_height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelf_length',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='width',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='Big Warehouse', max_length=256),
        ),
    ]
