# Generated by Django 3.2.5 on 2021-07-19 20:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_auto_20210719_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='grid',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='0', max_length=256), size=None), size=None), size=None),
        ),
    ]
