# Generated by Django 3.2.5 on 2021-07-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_auto_20210719_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='area',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='grid',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='leftover_x_space',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='x_grid_space',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='y_grid_space',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='z_grid_space',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelf_depth',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelf_height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelf_length',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='height',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='lane_width_size',
            field=models.IntegerField(default=48),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='length',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='Big Warehouse', max_length=256),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='width',
            field=models.IntegerField(default=600),
        ),
    ]
