# Generated by Django 3.2.5 on 2021-07-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_auto_20210720_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='measurement_unit',
            field=models.CharField(choices=[('feet', 'Feet'), ('inches', 'Inches')], default='feet', max_length=15),
        ),
    ]
