# Generated by Django 3.2.5 on 2021-07-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_auto_20210720_1644'),
        ('warehouses', '0003_auto_20210720_1851'),
    ]

    operations = [
    ]
