# Generated by Django 3.2.5 on 2021-07-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_warehouse_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='length',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='height',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='lane_width_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='shelf_depth',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='shelf_height',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='shelf_length',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='width',
            field=models.IntegerField(default=50),
        ),
    ]
