# Generated by Django 3.2.5 on 2021-07-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_auto_20210720_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='length',
            field=models.IntegerField(default=50),
        ),
    ]
