# Generated by Django 3.2.5 on 2021-07-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0006_warehouse_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='length',
            field=models.IntegerField(choices=[('feet', 'Feet'), ('inches', 'Inches')], default=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='measurement_unit',
            field=models.CharField(default='feet', max_length=15),
        ),
    ]
