# Generated by Django 3.2.5 on 2021-07-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_auto_20210720_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='length',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='measurement_unit',
            field=models.CharField(choices=[('feet', 'Feet'), ('inches', 'Inches')], default='feet', max_length=15),
        ),
    ]
