# Generated by Django 3.1.7 on 2021-07-19 21:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0013_auto_20210719_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='grid',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), size=None), size=None),
        ),
    ]
