# Generated by Django 3.1.7 on 2021-07-19 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0014_auto_20210719_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='grid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None),
        ),
    ]
