# Generated by Django 3.1.7 on 2021-07-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0016_auto_20210719_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='grid',
            field=models.JSONField(),
        ),
    ]
