# Generated by Django 3.1.7 on 2021-07-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0017_auto_20210719_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='grid',
            field=models.IntegerField(default=0),
        ),
    ]
