# Generated by Django 3.1.7 on 2021-07-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0018_auto_20210719_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='grid',
        ),
    ]
