# Generated by Django 3.1.7 on 2021-07-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0019_remove_warehouse_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='area',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='height',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='lane_width_size',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='leftover_x_space',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='length',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='width',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='x_grid_space',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='y_grid_space',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='z_grid_space',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='grid',
            field=models.IntegerField(default=0),
        ),
    ]
