# Generated by Django 3.1.7 on 2021-07-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0021_auto_20210719_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='shelf_layout',
            new_name='grid',
        ),
    ]
